# ----------------------------------------------------------------------------------------------------------------------
# 服务器设置
# 显示配置 @ComponentScan(basePackages = {"com.vivi.plugin"})
# ----------------------------------------------------------------------------------------------------------------------
server:
    # 设定http监听端口
    port: ${server_port}
# ----------------------------------------------------------------------------------------------------------------------
# spring 配置方案
# ----------------------------------------------------------------------------------------------------------------------
spring:
    application:
        name: "vivi-assistant"
    profiles:
        active:  dev
        group:
            assistant:
                - plugin
                - datasources
                - redis
                - rabbitmq
# ----------------------------------------------------------------------------------------------------------------------
